stages:
  - build

image: docker:dind

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - git config --global user.email "ci@northscaler.com"
    - git config --global user.name "Release Management"
    - apk add bash
    - bash -c ./test/polyrepos/test-all.sh
