stages:
  - build

image: docker:20.10.12

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: bitnami/git
  services:
    - docker:20.10.12-dind
  script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - ./test/test-all.sh
