stages:
  - build

image: docker:19.03.8

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  services:
    - docker:19.03.8-dind
  script:
    - ./test/test-all.sh
